# Generated by Django 4.0.3 on 2022-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Food', 'Food'), ('Culture', 'Culture'), ('Attractions', 'Attractions'), ('News', 'News'), ('Generic', 'Generic')], max_length=20)),
                ('travelphoto', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
